<a href="https://colab.research.google.com/github/dilni2004/ML-Labs/blob/main/Practice_ML_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
from sklearn.datasets import load_iris

iris = load_iris()

In [10]:
print("# of rows: ", iris.data.shape[0])
print("# of columns: ", iris.data.shape[1])
print("Feature names: ", iris.feature_names)
print("Target names: ", iris.target_names)

# of rows:  150
# of columns:  4
Feature names:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names:  ['setosa' 'versicolor' 'virginica']

In [20]:
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

df['target'] = iris.target
df['species'] = df['target'].apply(lambda x: iris.target_names[x])

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa

In [21]:
print("Shape: ", df.shape)
print("\nColumns: ", df.columns)
print("\nData Types: ", df.dtypes)
print("\nFirst Rows: ", df.head(5))
print("\nLast Rows: ", df.tail(5))

print("\nInformation: ", df.info)
print("\n Description: ", df.describe)

Shape:  (150, 6)

Columns:  Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target', 'species'],
      dtype='object')

Data Types:  sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
target                 int64
species               object
dtype: object

First Rows:     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

   target species
0       0  setosa
1       0  setosa
2       0  setosa
3       0  setosa
4       0  setosa

Last Rows:       sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

     target    species
145       2  virginica
146       2  virginica
147       2  virginica
148       2  virginica
149       2  virginica

Information:  <bound method DataFrame.info of      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

     target    species
0         0     setosa
1         0     setosa
2         0     setosa
3         0     setosa
4         0     setosa
..      ...        ...
145       2  virginica
146       2  virginica
147       2  virginica
148       2  virginica
149       2  virginica

[150 rows x 6 columns]>

 Description:  <bound method NDFrame.describe of      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

     target    species
0         0     setosa
1         0     setosa
2         0     setosa
3         0     setosa
4         0     setosa
..      ...        ...
145       2  virginica
146       2  virginica
147       2  virginica
148       2  virginica
149       2  virginica

[150 rows x 6 columns]>

In [22]:
print(df["species"].value_counts())

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

## Moment of truth

In [23]:
import numpy as np
import pandas as pd
import sklearn

In [26]:
from sklearn.datasets import load_iris

iris = load_iris()

print("# rows: ", iris.data.shape[0])
print("# columns: ", iris.data.shape[1])
print("# features: ", iris.feature_names)
print("# target: ", iris.target_names)

# rows:  150
# columns:  4
# features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
# target:  ['setosa' 'versicolor' 'virginica']

In [30]:
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

df['target'] = iris.target
df['species'] = df['target'].apply(lambda x: iris.target_names[x])

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa

In [33]:
print("Shape: ", df.shape)
print("\nColumns: ", df.columns)
print("\nData Types: ", df.dtypes)
print("\nFirst Rows: ", df.head(5))
print("\nLast Rows: ", df.tail(5))

print("\nInformation: ", df.info)
print("\n Description: ", df.describe)

Shape:  (150, 6)

Columns:  Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target', 'species'],
      dtype='object')

Data Types:  sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
target                 int64
species               object
dtype: object

First Rows:     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

   target species
0       0  setosa
1       0  setosa
2       0  setosa
3       0  setosa
4       0  setosa

Last Rows:       sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

     target    species
145       2  virginica
146       2  virginica
147       2  virginica
148       2  virginica
149       2  virginica

Information:  <bound method DataFrame.info of      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

     target    species
0         0     setosa
1         0     setosa
2         0     setosa
3         0     setosa
4         0     setosa
..      ...        ...
145       2  virginica
146       2  virginica
147       2  virginica
148       2  virginica
149       2  virginica

[150 rows x 6 columns]>

 Description:  <bound method NDFrame.describe of      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

     target    species
0         0     setosa
1         0     setosa
2         0     setosa
3         0     setosa
4         0     setosa
..      ...        ...
145       2  virginica
146       2  virginica
147       2  virginica
148       2  virginica
149       2  virginica

[150 rows x 6 columns]>

In [35]:
print(df['species'].value_counts())

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64